import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/Sidebar";
import Providers from "@/components/Providers";
import KeyboardShortcuts from "@/components/KeyboardShortcuts";
import TopNavBar from "@/components/TopNavBar";
import RightPanel from "@/components/RightPanel";
import StatusBar from "@/components/StatusBar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Providers>
          <KeyboardShortcuts />
          <div className="app-container">
            <TopNavBar />
            <div className="sidebar-wrapper">
              <Sidebar />
            </div>
            <main className="main-content">
              {children}
            </main>
            <RightPanel />
            <StatusBar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
